# Generated by Django 4.2.4 on 2023-09-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(blank=True, max_length=10)),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('contact_person_name', models.CharField(blank=True, max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=100)),
                ('site_readiness', models.CharField(blank=True, max_length=100)),
                ('aipl_dc_no', models.CharField(blank=True, max_length=100)),
                ('docket_no', models.CharField(blank=True, max_length=100)),
                ('bill_no', models.CharField(blank=True, max_length=100)),
                ('computer_desktop', models.CharField(blank=True, max_length=1000)),
                ('interactive_panel', models.CharField(blank=True, max_length=100)),
                ('invertor', models.CharField(blank=True, max_length=100)),
                ('io_device', models.CharField(blank=True, max_length=100)),
                ('hd_web_camera', models.CharField(blank=True, max_length=100)),
                ('ups_for_desktop', models.CharField(blank=True, max_length=1000)),
                ('pa_system', models.CharField(blank=True, max_length=100)),
                ('multi_printer', models.CharField(blank=True, max_length=100)),
                ('dev_mgmt_app', models.CharField(blank=True, max_length=100)),
                ('wifi_router', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
