# Generated by Django 4.2.4 on 2023-09-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data1',
            name='aipl_dc_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='bill_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='computer_desktop',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='contact_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='contact_person_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='dev_mgmt_app',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='docket_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='hd_web_camera',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='interactive_panel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='invertor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='io_device',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='location_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='multi_printer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='pa_system',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='school_id',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='site_readiness',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='ups_for_desktop',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='data1',
            name='wifi_router',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
